# -*- coding: utf-8 -*-
"""SHAP (rapido) - EUROMA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TnGB9joZJF0i88ZrgGGxCpsDLymXMaC
"""

# ============================================================
# BLOCK 0 — Setup & Imports
# ============================================================
import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split, StratifiedKFold,
    RandomizedSearchCV, GridSearchCV
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    make_scorer, f1_score, accuracy_score, matthews_corrcoef
)

# Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

RANDOM_STATE_BASE = 42
np.random.seed(RANDOM_STATE_BASE)

# ============================================================
# BLOCK 1 — Load data, clean labels, exclude unwanted classes, build X/y
# ============================================================
path = "/supplier_class3.xlsx"  # Colab: "/content/supplier_class2.xlsx"
df = pd.read_excel(path)

TARGET_COL = "performance_band"
ID_COL = "supplier_id"

print("Raw shape:", df.shape)
print("Columns:", list(df.columns))
display(df.head())

print("\nOriginal class distribution:")
print(df[TARGET_COL].value_counts(dropna=False))

def is_excluded_label(x):
    """
    Exclude labels that must not be used for supervised training.
    """
    if pd.isna(x):
        return True
    s = str(x).strip().upper()
    excluded = {"RANDOM", "FICAR", "PARA FICAR", "KEEP", "TO KEEP"}
    return s in excluded

df_clean = df.loc[~df[TARGET_COL].apply(is_excluded_label)].copy()

def coerce_class_to_int(v):
    """
    Coerce target labels to integer classes {0,1,2}.
    Supports numeric labels and common textual labels.
    """
    if isinstance(v, (int, np.integer)):
        return int(v)
    if isinstance(v, (float, np.floating)) and float(v).is_integer():
        return int(v)

    s = str(v).strip().upper()
    mapping = {
        "0": 0, "1": 1, "2": 2,
        "RUIM": 0, "POBRE": 0, "BAD": 0,
        "MÉDIO": 1, "MEDIO": 1, "AVERAGE": 1, "MIDDLE": 1,
        "BOM": 2, "GOOD": 2
    }
    if s in mapping:
        return mapping[s]
    raise ValueError(f"Unexpected target label: {v}")

y = df_clean[TARGET_COL].apply(coerce_class_to_int).astype(int)

drop_cols = [TARGET_COL]
if ID_COL in df_clean.columns:
    drop_cols.append(ID_COL)

feature_cols = [c for c in df_clean.columns if c not in drop_cols]
X = df_clean[feature_cols].copy()

print("\nAfter exclusion shape:", df_clean.shape)
print("Final y distribution:")
print(y.value_counts().sort_index())
print("\nNumber of features:", X.shape[1])
print("Features:", feature_cols)

import seaborn as sns
sns.heatmap(X.corr(), annot=True)

# ============================================================
# BLOCK 2 — TEMPORÁRIO
# ============================================================

# ============================================================
# BLOCK 2 (FAST TEST VERSION) — Models + Narrow Random Search Space
# Random Search only (no Grid Search) to speed up Phase 1.
# ============================================================

from sklearn.model_selection import StratifiedKFold

# Primary tuning/selection metric
scoring = {
    "macro_f1": make_scorer(f1_score, average="macro"),
    "accuracy": make_scorer(accuracy_score),
    "mcc": make_scorer(matthews_corrcoef)
}
REFIT_METRIC = "macro_f1"

# Models (scaling only where needed)
models = {
    "KNN": Pipeline([("scaler", StandardScaler()), ("model", KNeighborsClassifier())]),
    "SVM": Pipeline([("scaler", StandardScaler()), ("model", SVC())]),
    "LogReg": Pipeline([("scaler", StandardScaler()), ("model", LogisticRegression(max_iter=3000))]),
    "NaiveBayes": Pipeline([("scaler", StandardScaler()), ("model", GaussianNB())]),
    "DecisionTree": Pipeline([("model", DecisionTreeClassifier(random_state=RANDOM_STATE_BASE))]),
    "RandomForest": Pipeline([("model", RandomForestClassifier(random_state=RANDOM_STATE_BASE, n_jobs=-1))]),
    "GradientBoosting": Pipeline([("model", GradientBoostingClassifier(random_state=RANDOM_STATE_BASE))]),
}

# -------------------------------------------
# Narrower search spaces (fast smoke test)
# -------------------------------------------
param_distributions = {
    "KNN": {
        # smaller range to speed up
        "model__n_neighbors": np.arange(3, 31, 2),     # 3..29 step 2
        "model__weights": ["uniform", "distance"],
        "model__p": [1, 2],
        "model__leaf_size": np.arange(20, 61, 10)      # 20,30,40,50,60
    },
    "SVM": {
        # narrower C range; kernel reduced
        "model__C": np.logspace(-1, 2, 15),            # 0.1..100
        "model__kernel": ["rbf", "linear"],
        "model__gamma": ["scale"]                      # fixed to reduce cost
    },
    "LogReg": {
        "model__C": np.logspace(-2, 2, 15),            # 0.01..100
        "model__penalty": ["l2"],
        "model__solver": ["lbfgs"]                     # fixed to reduce variability
    },
    "NaiveBayes": {
        "model__var_smoothing": np.logspace(-11, -8, 12)  # narrower
    },
    "DecisionTree": {
        "model__criterion": ["gini", "entropy"],
        "model__max_depth": [None, 5, 10, 15, 20],
        "model__min_samples_split": [2, 5, 10, 20],
        "model__min_samples_leaf": [1, 2, 5, 10],
        "model__ccp_alpha": np.linspace(0.0, 0.01, 8)
    },
    "RandomForest": {
        # reduce estimators and depth choices
        "model__n_estimators": [150, 250, 350, 450],
        "model__max_depth": [None, 8, 12, 16, 20],
        "model__min_samples_split": [2, 5, 10],
        "model__min_samples_leaf": [1, 2, 4],
        "model__max_features": ["sqrt", "log2"]
    },
    "GradientBoosting": {
        "model__n_estimators": [100, 200, 300],
        "model__learning_rate": [0.03, 0.05, 0.1],
        "model__max_depth": [2, 3],
        "model__subsample": [0.8, 1.0]
    }
}

# Fast tuning settings (Phase 1 test)
N_SPLITS_INNER = 3         # was 5
N_ITER_RANDOM = 20         # was 40+
INNER_CV_TEMPLATE = StratifiedKFold(n_splits=N_SPLITS_INNER, shuffle=True, random_state=RANDOM_STATE_BASE)

print("FAST TEST settings:")
print("Inner CV splits:", N_SPLITS_INNER)
print("RandomSearch n_iter:", N_ITER_RANDOM)
print("Models:", list(models.keys()))

# ============================================================
# BLOCK 3 (FAST TEST) — PHASE 1 with 40 external rounds (Random Search only)
# ============================================================

N_ROUNDS_EXTERNAL = 40
TEST_SIZE = 0.20

records = []

for rnd in range(N_ROUNDS_EXTERNAL):
    rnd_seed = RANDOM_STATE_BASE + rnd

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=rnd_seed, stratify=y
    )

    # inner CV changes each round (still reproducible)
    inner_cv = StratifiedKFold(n_splits=N_SPLITS_INNER, shuffle=True, random_state=rnd_seed)

    for model_name, pipe in models.items():
        rs = RandomizedSearchCV(
            estimator=pipe,
            param_distributions=param_distributions[model_name],
            n_iter=N_ITER_RANDOM,
            scoring=scoring,
            refit=REFIT_METRIC,
            cv=inner_cv,
            random_state=rnd_seed,
            n_jobs=-1,
            verbose=0
        )
        rs.fit(X_train, y_train)

        best_est = rs.best_estimator_
        y_pred = best_est.predict(X_test)

        records.append({
            "round": rnd,
            "seed": rnd_seed,
            "model": model_name,
            "test_macro_f1": f1_score(y_test, y_pred, average="macro"),
            "test_accuracy": accuracy_score(y_test, y_pred),
            "test_mcc": matthews_corrcoef(y_test, y_pred),
            "inner_cv_best_macro_f1": rs.best_score_,
            "best_params": str(rs.best_params_)
        })

    if (rnd + 1) % 5 == 0:
        print(f"Completed rounds: {rnd+1}/{N_ROUNDS_EXTERNAL}")

results_long = pd.DataFrame(records)
display(results_long.head())
print("Shape:", results_long.shape)

# ============================================================
# BLOCK 4 — PHASE 1 summary: mean ± std and automatic winner
# ============================================================

summary = (
    results_long
    .groupby("model")[["test_macro_f1", "test_accuracy", "test_mcc"]]
    .agg(["mean", "std"])
)
summary.columns = ["_".join(c) for c in summary.columns]
summary = summary.sort_values(by="test_macro_f1_mean", ascending=False)

display(summary)

winner_by_mean = summary.index[0]
print("\nWinner by mean Macro F1:", winner_by_mean)

# ============================================================
# BLOCK 5 — PHASE 1 statistics (Macro F1): Friedman + Wilcoxon Holm vs winner
# ============================================================
from scipy.stats import friedmanchisquare, wilcoxon

def holm_correction(p_values):
    m = len(p_values)
    order = np.argsort(p_values)
    adjusted = np.empty(m, dtype=float)
    for k, idx in enumerate(order):
        adjusted[idx] = min(1.0, (m - k) * p_values[idx])
    # enforce monotonicity
    adj_sorted = adjusted[order]
    adj_sorted = np.maximum.accumulate(adj_sorted)
    adjusted[order] = adj_sorted
    return adjusted

# Wide format for Macro F1: rows=rounds, cols=models (paired by round)
macro_wide = results_long.pivot(index="round", columns="model", values="test_macro_f1").sort_index()
display(macro_wide.head())

# Friedman global test
cols = [macro_wide[c].values for c in macro_wide.columns]
stat, p = friedmanchisquare(*cols)
print(f"Friedman (Macro F1): statistic={stat:.6f}, p-value={p:.6g}")

# Winner by mean Macro F1 (on macro_wide)
means = macro_wide.mean(axis=0).sort_values(ascending=False)
winner = means.index[0]
print("Winner (Macro F1 mean):", winner)

# Post-hoc: Wilcoxon paired vs winner + Holm
base = macro_wide[winner].values
posthoc = []

for model_name in macro_wide.columns:
    if model_name == winner:
        continue
    try:
        w_stat, w_p = wilcoxon(base, macro_wide[model_name].values, zero_method="wilcox", alternative="two-sided")
    except Exception:
        w_stat, w_p = np.nan, 1.0
    posthoc.append({"winner": winner, "compared_model": model_name, "wilcoxon_stat": w_stat, "p_value": w_p})

posthoc = pd.DataFrame(posthoc)
posthoc["p_value_holm"] = holm_correction(posthoc["p_value"].values)
posthoc = posthoc.sort_values("p_value_holm")
display(posthoc)

# Automatic selection rule (simple and defensible):
# - Choose the winner by mean Macro F1.
# - If Friedman p<0.05, we can say there are significant differences overall.
# - Post-hoc helps justify differences vs specific competitors.
SELECTED_ALGO = winner
print("\nSELECTED_ALGO (for Phase 2):", SELECTED_ALGO)

# ============================================================
# BLOCK 6 — PHASE 2 (FAST): Final hyperparameter tuning on full dataset
# RandomSearchCV only (no refined GridSearch)
# ============================================================

FINAL_CV_SPLITS = 10
FINAL_RANDOM_ITER = 200  # pode reduzir p/ 80-120 se estiver pesado

final_cv = StratifiedKFold(
    n_splits=FINAL_CV_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE_BASE
)

pipe = models[SELECTED_ALGO]

final_rs = RandomizedSearchCV(
    estimator=pipe,
    param_distributions=param_distributions[SELECTED_ALGO],
    n_iter=FINAL_RANDOM_ITER,
    scoring=scoring,
    refit=REFIT_METRIC,
    cv=final_cv,
    random_state=RANDOM_STATE_BASE,
    n_jobs=-1,
    verbose=0
)

final_rs.fit(X, y)

FINAL_MODEL = final_rs.best_estimator_
FINAL_PARAMS = final_rs.best_params_
FINAL_CV_BEST = final_rs.best_score_

print("\nFINAL MODEL SELECTED:", SELECTED_ALGO)
print("FINAL CV macro_f1:", FINAL_CV_BEST)
print("FINAL PARAMS:", FINAL_PARAMS)

# ============================================================
# BLOCK 7 — Save artifacts (works with Route A)
# ============================================================
import pickle

artifacts = {
    "selected_algorithm": SELECTED_ALGO,
    "final_model": FINAL_MODEL,
    "final_params": FINAL_PARAMS,
    "final_cv_best_macro_f1": FINAL_CV_BEST,
    "feature_names": list(X.columns),
    "phase1_results_long": results_long,   # if you ran Phase 1
}

with open("final_model_and_results.pkl", "wb") as f:
    pickle.dump(artifacts, f)

# Optional saves
results_long.to_excel("phase1_external_results_long.xlsx", index=False)

print("Saved:")
print("- final_model_and_results.pkl")
print("- phase1_external_results_long.xlsx")

# ============================================================
# SHAP BLOCK 0 — Install & imports
# ============================================================
!pip -q install shap

import shap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

shap.initjs()

RANDOM_STATE_SHAP = RANDOM_STATE_BASE  # keep reproducible

# ============================================================
# SHAP BLOCK 1 — Prepare transformed X and select a SHAP evaluation subset
# ============================================================

def get_estimator_and_X(pipeline, X_df):
    """Return fitted estimator and transformed X (if scaler exists)."""
    if isinstance(pipeline, Pipeline):
        steps = dict(pipeline.named_steps)
        X_trans = steps["scaler"].transform(X_df) if "scaler" in steps else X_df.values
        est = steps["model"]
        return est, X_trans
    return pipeline, X_df.values

estimator, X_trans = get_estimator_and_X(FINAL_MODEL, X)
feature_names = list(X.columns)

# Choose subset size for SHAP (speed vs coverage)
EVAL_SIZE = min(300, X_trans.shape[0])
BG_SIZE   = min(200, X_trans.shape[0])

rng = np.random.default_rng(RANDOM_STATE_SHAP)
ev_idx = rng.choice(X_trans.shape[0], size=EVAL_SIZE, replace=False)
bg_idx = rng.choice(X_trans.shape[0], size=BG_SIZE, replace=False)

X_eval = X_trans[ev_idx]
X_bg   = X_trans[bg_idx]

print("SELECTED_ALGO:", SELECTED_ALGO)
print("X_eval:", X_eval.shape, "| X_bg:", X_bg.shape)

# ============================================================
# SHAP BLOCK 2 — Compute SHAP once and create "old-style" arrays
# ============================================================

tree_models = {"DecisionTree", "RandomForest", "GradientBoosting"}

if SELECTED_ALGO in tree_models:
    explainer = shap.TreeExplainer(estimator)
    shap_exp = explainer(X_eval)

elif isinstance(estimator, LogisticRegression):
    explainer = shap.LinearExplainer(estimator, X_bg)
    shap_exp = explainer(X_eval)

else:
    # Generic (works for many classifiers; may be slower for some)
    explainer = shap.Explainer(estimator.predict_proba, X_bg)
    shap_exp = explainer(X_eval)

# "Notebook-like" objects:
shap_values_like = shap_exp.values       # (n_eval, n_features, n_classes)
base_values_like = shap_exp.base_values  # (n_eval, n_classes) in multiclass

print("shap_values_like shape:", shap_values_like.shape)
print("base_values_like shape:", np.array(base_values_like).shape)
print("Example: local i=0 corresponds to original row:", int(ev_idx[0]))

# ============================================
# SHAP BLOCK 3 – Beeswarm plots
# ============================================

class_name_map = {
    0: "Poor",
    1: "Average",
    2: "Good"
}

class_names = [class_name_map[i] for i in range(len(class_name_map))]

# Overall summary (works with multiclass Explanation)
shap.summary_plot(
    shap_exp,
    X_eval,
    feature_names=feature_names,
    class_names=class_names
)

# Optional: per-class beeswarm (if multiclass)
vals = shap_values_like
if vals.ndim == 3:
    n_classes = vals.shape[2]
    for c in range(n_classes):
        class_label = class_name_map.get(c, f"Class {c}")
        print(f"\nBeeswarm - {class_label}")
        shap.summary_plot(
            vals[:, :, c],
            X_eval,
            feature_names=feature_names,
            show=True
        )

# ============================================================
# SHAP BLOCK 3 — Beeswarm plots
# ============================================================


# Overall summary (works with multiclass Explanation)
shap.summary_plot(shap_exp, X_eval, feature_names=feature_names)


# Optional: per-class beeswarm (if multiclass)
vals = shap_values_like
if vals.ndim == 3:
    n_classes = vals.shape[2]
    for c in range(n_classes):
        print(f"\nBeeswarm — class {c}")
        shap.summary_plot(vals[:, :, c], X_eval, feature_names=feature_names, show=True)



# ============================================================
# SHAP BLOCK 4 — Waterfall: choose observation i and class c (simple)
# ============================================================

def waterfall(i, c, max_display=20):
    """
    i: local index within SHAP evaluation subset (0..EVAL_SIZE-1)
    c: class index (0,1,2)
    """
    exp_1d = shap.Explanation(
        values=shap_values_like[i, :, c],
        base_values=base_values_like[i, c] if np.ndim(base_values_like) > 1 else base_values_like[i],
        data=X_eval[i, :],
        feature_names=feature_names
    )
    print(f"Waterfall | local i={i} | original row={int(ev_idx[i])} | class={c}")
    shap.plots.waterfall(exp_1d, max_display=max_display)

# Examples (same spirit as your notebook)
waterfall(12, 0)
waterfall(12, 1)
waterfall(12, 2)

# ============================================================
# SHAP BLOCK 5 — SHAP tables for a single observation i (3 classes)
# ============================================================

i = 25  # change this freely

shap_class_0 = shap_values_like[i, :, 0]
shap_class_1 = shap_values_like[i, :, 1]
shap_class_2 = shap_values_like[i, :, 2]

df_shap_0 = pd.DataFrame({"Feature": feature_names, "SHAP Value": shap_class_0})
df_shap_1 = pd.DataFrame({"Feature": feature_names, "SHAP Value": shap_class_1})
df_shap_2 = pd.DataFrame({"Feature": feature_names, "SHAP Value": shap_class_2})

print(f"Local i={i} | Original row={int(ev_idx[i])}")

print("\nClass 0:")
display(df_shap_0.sort_values("SHAP Value", ascending=False).head(20))

print("\nClass 1:")
display(df_shap_1.sort_values("SHAP Value", ascending=False).head(20))

print("\nClass 2:")
display(df_shap_2.sort_values("SHAP Value", ascending=False).head(20))

# ============================================================
# SHAP BLOCK 6 — Feature weights per class (mean |SHAP|)
# + grouped vertical bar plot (one bar per class for each feature)
# ============================================================

vals = shap_values_like
n_classes = vals.shape[2]

mean_abs = np.array([np.mean(np.abs(vals[:, :, c]), axis=0) for c in range(n_classes)])  # (classes, features)

df_class_weights = pd.DataFrame(
    mean_abs.T,
    columns=[f"Class {c}" for c in range(n_classes)],
    index=feature_names
)

# Select Top-K by global sum for readability
df_class_weights["Global_sum"] = df_class_weights.sum(axis=1)
TOP_K = 15
df_plot = df_class_weights.sort_values("Global_sum", ascending=False).head(TOP_K).drop(columns=["Global_sum"])

display(df_plot)

# Grouped vertical bars
x = np.arange(df_plot.shape[0])
width = 0.25 if n_classes == 3 else 0.8 / n_classes

plt.figure(figsize=(14, 6))
for c in range(n_classes):
    plt.bar(x + (c - (n_classes-1)/2)*width, df_plot[f"Class {c}"].values, width=width, label=f"Class {c}")

plt.xticks(x, df_plot.index, rotation=45, ha="right")
plt.ylabel("mean(|SHAP|)")
plt.title(f"Class-wise SHAP weights (Top {TOP_K}) — grouped bars")
plt.legend()
plt.tight_layout()
plt.show()

df_class_weights.drop(columns=["Global_sum"], errors="ignore").to_excel("shap_weights_by_class.xlsx")
print("Saved: shap_weights_by_class.xlsx")

# ============================================================
# SHAP BLOCK 7 — Global weights (vertical bars per criterion)
# ============================================================

# (Re)compute df_global safely
class_cols = [c for c in df_class_weights.columns if c.startswith("Class")]

df_global = pd.DataFrame(index=feature_names)
df_global["Global_weight"] = df_class_weights[class_cols].sum(axis=1)
df_global = df_global.sort_values("Global_weight", ascending=False)
df_global["Normalized_weight"] = df_global["Global_weight"] / df_global["Global_weight"].sum()

display(df_global.head(25))

# ---- Plot (safe TOP_K)
TOP_K_GLOBAL = 20
k = min(TOP_K_GLOBAL, df_global.shape[0])

x = np.arange(k)
y = df_global["Normalized_weight"].head(k).values
labels = df_global.head(k).index.tolist()

plt.figure(figsize=(12, 5))
plt.bar(x, y)  # vertical bars
plt.xticks(x, labels, rotation=45, ha="right")
plt.ylabel("Normalized global weight")
plt.title(f"Global SHAP weights (Top {k})")
plt.tight_layout()
plt.show()

df_global.to_excel("shap_global_weights.xlsx")
print("Saved: shap_global_weights.xlsx")

0.28*(100 - defect_rate_pct) +
    0.26*(on_time_delivery_pct) +
    0.18*(100 * (1 - financial_risk_prob_default)) +
    0.18*(100 - normalized price_index_vs_market) +
    0.10*(sustainability_score)



"""   0.28*(100 - defect_rate_pct) +
    0.26*(on_time_delivery_pct) +
    0.18*(100 * (1 - financial_risk_prob_default)) +
    0.18*(100 - normalized price_index_vs_market) +
    0.10*(sustainability_score)
"""

import seaborn as sns
sns.heatmap(X.corr(), annot=True)